//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kf2_server_gui.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("kf2_server_gui.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Password.
        /// </summary>
        public static string AdminPassword {
            get {
                return ResourceManager.GetString("AdminPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The administrative user&apos;s password.
        ///
        ///IMPORTANT: This is not secure and will be stored as plaintext. Do not use a password you use elsewhere here..
        /// </summary>
        public static string AdminPasswordToolTip {
            get {
                return ResourceManager.GetString("AdminPasswordToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Username.
        /// </summary>
        public static string AdminUsername {
            get {
                return ResourceManager.GetString("AdminUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the administrative user.
        /// </summary>
        public static string AdminUsernameToolTip {
            get {
                return ResourceManager.GetString("AdminUsernameToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server directory is not valid or does not exist. Mouse over the labels for some tips..
        /// </summary>
        public static string BadServerDirectory {
            get {
                return ResourceManager.GetString("BadServerDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to steamcmd path is not valid. Mouse over the labels for some tips..
        /// </summary>
        public static string BadSteamcmdPath {
            get {
                return ResourceManager.GetString("BadSteamcmdPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The update script is invalid. At a minimum, it must contain a line like &quot;app_update {0}&quot;..
        /// </summary>
        public static string BadUpdateScript {
            get {
                return ResourceManager.GetString("BadUpdateScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close the window.
        /// </summary>
        public static string CloseToolTip {
            get {
                return ResourceManager.GetString("CloseToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command Line.
        /// </summary>
        public static string CommandLine {
            get {
                return ResourceManager.GetString("CommandLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using this command line to start the server:.
        /// </summary>
        public static string CommandLineIntro {
            get {
                return ResourceManager.GetString("CommandLineIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A map will be selected randomly each time you display the command line, start the server, or restart the server..
        /// </summary>
        public static string CommandLineRandom {
            get {
                return ResourceManager.GetString("CommandLineRandom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display the command line….
        /// </summary>
        public static string CommandLineToolTip {
            get {
                return ResourceManager.GetString("CommandLineToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to write the update script. This file is written to the KF2 server folder..
        /// </summary>
        public static string CouldNotWriteUpdateScript {
            get {
                return ResourceManager.GetString("CouldNotWriteUpdateScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write Error.
        /// </summary>
        public static string CouldNotWriteUpdateScriptCaption {
            get {
                return ResourceManager.GetString("CouldNotWriteUpdateScriptCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark style.
        /// </summary>
        public static string DarkStyle {
            get {
                return ResourceManager.GetString("DarkStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No judgment here, use whichever you prefer!.
        /// </summary>
        public static string DarkStyleToolTip {
            get {
                return ResourceManager.GetString("DarkStyleToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to changeme.
        /// </summary>
        public static string DefaultAdminPassword {
            get {
                return ResourceManager.GetString("DefaultAdminPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to admin.
        /// </summary>
        public static string DefaultAdminUsername {
            get {
                return ResourceManager.GetString("DefaultAdminUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //
        ///login anonymous
        ///force_install_dir {0}
        ///app_update 232130
        ///exit.
        /// </summary>
        public static string DefaultUpdateScript {
            get {
                return ResourceManager.GetString("DefaultUpdateScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Difficulty.
        /// </summary>
        public static string Difficulty {
            get {
                return ResourceManager.GetString("Difficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the server difficulty.
        /// </summary>
        public static string DifficultyToolTip {
            get {
                return ResourceManager.GetString("DifficultyToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endless.
        /// </summary>
        public static string Endless {
            get {
                return ResourceManager.GetString("Endless", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra Options.
        /// </summary>
        public static string ExtraOptions {
            get {
                return ResourceManager.GetString("ExtraOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify any extra options you want to pass to the server. Start each option with a question mark and do not use spaces. Find these in the console output and refer to the Killing Floor 2 wiki (or Google) for help..
        /// </summary>
        public static string ExtraOptionsToolTip {
            get {
                return ResourceManager.GetString("ExtraOptionsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Length.
        /// </summary>
        public static string GameLength {
            get {
                return ResourceManager.GetString("GameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length of each game (4 waves, 7 waves, or 10 waves).
        /// </summary>
        public static string GameLengthToolTip {
            get {
                return ResourceManager.GetString("GameLengthToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your preferred game mode.
        /// </summary>
        public static string GameModeToolTip {
            get {
                return ResourceManager.GetString("GameModeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hard.
        /// </summary>
        public static string Hard {
            get {
                return ResourceManager.GetString("Hard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hell on Earth.
        /// </summary>
        public static string HellOnEarth {
            get {
                return ResourceManager.GetString("HellOnEarth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Killing Floor 2 Server Folder.
        /// </summary>
        public static string KF2ServerFolder {
            get {
                return ResourceManager.GetString("KF2ServerFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the Killing Floor 2 server folder….
        /// </summary>
        public static string KF2ServerFolderBrowseToolTip {
            get {
                return ResourceManager.GetString("KF2ServerFolderBrowseToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the folder that contains your Killing Floor 2 server.
        /// </summary>
        public static string KF2ServerFolderToolTip {
            get {
                return ResourceManager.GetString("KF2ServerFolderToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long.
        /// </summary>
        public static string Long {
            get {
                return ResourceManager.GetString("Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload the available maps.
        /// </summary>
        public static string MapRefreshToolTip {
            get {
                return ResourceManager.GetString("MapRefreshToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Player Count.
        /// </summary>
        public static string MaxPlayerCount {
            get {
                return ResourceManager.GetString("MaxPlayerCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum number of players that can connect to the server.
        /// </summary>
        public static string MaxPlayerCountToolTip {
            get {
                return ResourceManager.GetString("MaxPlayerCountToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        public static string Medium {
            get {
                return ResourceManager.GetString("Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string Normal {
            get {
                return ResourceManager.GetString("Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick a Random Map.
        /// </summary>
        public static string RandomMap {
            get {
                return ResourceManager.GetString("RandomMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready to update server.
        /// </summary>
        public static string ReadyToUpdate {
            get {
                return ResourceManager.GetString("ReadyToUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart the server.
        /// </summary>
        public static string RestartToolTip {
            get {
                return ResourceManager.GetString("RestartToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A starting map must be selected.
        /// </summary>
        public static string SelectAMap {
            get {
                return ResourceManager.GetString("SelectAMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server is running.
        /// </summary>
        public static string ServerIsRunning {
            get {
                return ResourceManager.GetString("ServerIsRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server directory is valid; server is not running.
        /// </summary>
        public static string ServerIsStopped {
            get {
                return ResourceManager.GetString("ServerIsStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short.
        /// </summary>
        public static string Short {
            get {
                return ResourceManager.GetString("Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting Map.
        /// </summary>
        public static string StartingMap {
            get {
                return ResourceManager.GetString("StartingMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick the first map players will join.
        /// </summary>
        public static string StartingMapToolTip {
            get {
                return ResourceManager.GetString("StartingMapToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start the server….
        /// </summary>
        public static string StartToolTip {
            get {
                return ResourceManager.GetString("StartToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to steamcmd.
        /// </summary>
        public static string SteamcmdPath {
            get {
                return ResourceManager.GetString("SteamcmdPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the steamcmd executable….
        /// </summary>
        public static string SteamcmdPathBrowseToolTip {
            get {
                return ResourceManager.GetString("SteamcmdPathBrowseToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the path to your steamcmd executable.
        /// </summary>
        public static string SteamcmdPathToolTip {
            get {
                return ResourceManager.GetString("SteamcmdPathToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop the server.
        /// </summary>
        public static string StopToolTip {
            get {
                return ResourceManager.GetString("StopToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suicidal.
        /// </summary>
        public static string Suicidal {
            get {
                return ResourceManager.GetString("Suicidal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survival.
        /// </summary>
        public static string Survival {
            get {
                return ResourceManager.GetString("Survival", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Server.
        /// </summary>
        public static string UpdateServer {
            get {
                return ResourceManager.GetString("UpdateServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following script will be used to update the server. Feel free to modify it and your changes will be saved..
        /// </summary>
        public static string UpdateServerIntro {
            get {
                return ResourceManager.GetString("UpdateServerIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The default script should work well for you in most instances.
        /// </summary>
        public static string UpdateServerIntroToolTip {
            get {
                return ResourceManager.GetString("UpdateServerIntroToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update the server….
        /// </summary>
        public static string UpdateToolTip {
            get {
                return ResourceManager.GetString("UpdateToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating server.
        /// </summary>
        public static string UpdatingServer {
            get {
                return ResourceManager.GetString("UpdatingServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate server files after downloading.
        /// </summary>
        public static string ValidateAfterDownloading {
            get {
                return ResourceManager.GetString("ValidateAfterDownloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is probably not needed, but use it if you tend to get corrupted files during the update.
        /// </summary>
        public static string ValidateAfterDownloadingToolTip {
            get {
                return ResourceManager.GetString("ValidateAfterDownloadingToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} version {1}.
        /// </summary>
        public static string VersionString {
            get {
                return ResourceManager.GetString("VersionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Versus Survival.
        /// </summary>
        public static string Versus {
            get {
                return ResourceManager.GetString("Versus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly Outbreaks.
        /// </summary>
        public static string Weekly {
            get {
                return ResourceManager.GetString("Weekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Killing Floor 2 Server GUI.
        /// </summary>
        public static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
    }
}
